apiVersion: v1
data:
  mapRoles: |
$ROLE
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::512091347803:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1RS9K9TF1O3D6
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::512091347803:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-07T17:09:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "147297"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 966d5276-78f2-11ea-baa8-0e9dcfbedc14
